#ifndef _CUST_BAT_H_
#define _CUST_BAT_H_

/* stop charging while in talking mode */
#define STOP_CHARGING_IN_TAKLING
#define TALKING_RECHARGE_VOLTAGE   3800
#define TALKING_SYNC_TIME		   60

/* Battery Temperature Protection */
#define MTK_TEMPERATURE_RECHARGE_SUPPORT
#define MAX_CHARGE_TEMPERATURE                  53
#define MAX_CHARGE_TEMPERATURE_MINUS_X_DEGREE   50 //47 Fixed to 50 degree for according to TCL standard
#define MIN_CHARGE_TEMPERATURE                  2
#define MIN_CHARGE_TEMPERATURE_PLUS_X_DEGREE    4  //6 Fixed to 2 degree accoding to TCL standard
#define MAX_LIMIT_CHARGE_TEMPERATURE            43
/* [PLATFORM]-ADD-BEGIN by TCTSZ leo.guo, 06/09/2015,  BATTERY Notify for NTC*/
#define MAX_RAISING_CHARGE_TEMPERATURE          56 //58 Fixed to 56 degree for according to TCL standard
#define MIN_DROPPING_CHARGE_TEMPERATURE        -16 //-18 Fixed to -16 degree for according to TCL standard
/* [PLATFORM]-ADD-END by TCTSZ leo.guo*/
#define ERR_CHARGE_TEMPERATURE  0xFF

/* Linear Charging Threshold */
#define V_PRE2CC_THRES	 		3400	//mV
#define V_CC2TOPOFF_THRES		4150
#define RECHARGING_VOLTAGE      4200
#define CHARGING_FULL_CURRENT   100	//mA

/* Charging Current Setting */
//#define CONFIG_USB_IF
#define USB_CHARGER_CURRENT_SUSPEND			0		// def CONFIG_USB_IF
#define USB_CHARGER_CURRENT_UNCONFIGURED	CHARGE_CURRENT_70_00_MA	// 70mA
#define USB_CHARGER_CURRENT_CONFIGURED		CHARGE_CURRENT_500_00_MA	// 500mA

#define USB_CHARGER_CURRENT					CHARGE_CURRENT_500_00_MA	//500mA
#define AC_CHARGER_CURRENT				    CHARGE_CURRENT_1000_00_MA //Fixed the charging current according to HW.
#define NON_STD_AC_CHARGER_CURRENT			CHARGE_CURRENT_500_00_MA
#define CHARGING_HOST_CHARGER_CURRENT       CHARGE_CURRENT_650_00_MA
#define APPLE_0_5A_CHARGER_CURRENT          CHARGE_CURRENT_500_00_MA
#define APPLE_1_0A_CHARGER_CURRENT          CHARGE_CURRENT_650_00_MA
#define APPLE_2_1A_CHARGER_CURRENT          CHARGE_CURRENT_800_00_MA


/* Precise Tunning */
#define BATTERY_AVERAGE_DATA_NUMBER	3
#define BATTERY_AVERAGE_SIZE 	30

/* charger error check */
#define BAT_LOW_TEMP_PROTECT_ENABLE     // stop charging if temp < MIN_CHARGE_TEMPERATURE
#define V_CHARGER_ENABLE 0				// 1:ON , 0:OFF	
#define V_CHARGER_MAX 6500				// 6.5 V
#define V_CHARGER_MAX 6200				// 6.2 V
#define V_CHARGER_MIN 4400				// 4.4 V

/* Tracking TIME */
#define ONEHUNDRED_PERCENT_TRACKING_TIME	10	 // 10 second
#define NPERCENT_TRACKING_TIME	   			20	 // 20 second
#define SYNC_TO_REAL_TRACKING_TIME  		60	 // 60 second
#define V_0PERCENT_TRACKING				    3400 //3450mV

/* Battery Notify */
#define BATTERY_NOTIFY_CASE_0001_VCHARGER
#define BATTERY_NOTIFY_CASE_0002_VBATTEMP
//#define BATTERY_NOTIFY_CASE_0003_ICHARGING
//#define BATTERY_NOTIFY_CASE_0004_VBAT
//#define BATTERY_NOTIFY_CASE_0005_TOTAL_CHARGINGTIME

/* JEITA parameter */
//#define MTK_JEITA_STANDARD_SUPPORT
#define CUST_SOC_JEITA_SYNC_TIME 30
#define JEITA_RECHARGE_VOLTAGE  4110	// for linear charging
#define JEITA_TEMP_ABOVE_POS_60_CV_VOLTAGE		BATTERY_VOLT_04_100000_V
#define JEITA_TEMP_POS_45_TO_POS_60_CV_VOLTAGE	BATTERY_VOLT_04_100000_V
#define JEITA_TEMP_POS_10_TO_POS_45_CV_VOLTAGE	BATTERY_VOLT_04_200000_V
#define JEITA_TEMP_POS_0_TO_POS_10_CV_VOLTAGE	BATTERY_VOLT_04_100000_V
#define JEITA_TEMP_NEG_10_TO_POS_0_CV_VOLTAGE	BATTERY_VOLT_03_900000_V
#define JEITA_TEMP_BELOW_NEG_10_CV_VOLTAGE		BATTERY_VOLT_03_900000_V

/* For JEITA Linear Charging only */
#define JEITA_NEG_10_TO_POS_0_FULL_CURRENT  120	//mA 
#define JEITA_TEMP_POS_45_TO_POS_60_RECHARGE_VOLTAGE  4000
#define JEITA_TEMP_POS_10_TO_POS_45_RECHARGE_VOLTAGE  4100
#define JEITA_TEMP_POS_0_TO_POS_10_RECHARGE_VOLTAGE   4000
#define JEITA_TEMP_NEG_10_TO_POS_0_RECHARGE_VOLTAGE   3800
#define JEITA_TEMP_POS_45_TO_POS_60_CC2TOPOFF_THRESHOLD	4050
#define JEITA_TEMP_POS_10_TO_POS_45_CC2TOPOFF_THRESHOLD	4050
#define JEITA_TEMP_POS_0_TO_POS_10_CC2TOPOFF_THRESHOLD	4050
#define JEITA_TEMP_NEG_10_TO_POS_0_CC2TOPOFF_THRESHOLD	3850


/* High battery support */
#define HIGH_BATTERY_VOLTAGE_SUPPORT

/* Disable Battery check for HQA */
#ifdef CONFIG_MTK_DISABLE_POWER_ON_OFF_VOLTAGE_LIMITATION
#define CONFIG_DIS_CHECK_BATTERY
#endif

/* [PLATFORM]-Add-BEGIN by TCTSZ.leo.guo, 04/15/2015,  modify ntc temperature function */
#define MTK_BATTERY_PROTECT_FEATURE
/* [PLATFORM]-Add-END by TCTSZ.leo.guo */

/* [PLATFORM]-Add-BEGIN by TCTSZ.pingao.yang, 09/07/2015,  add charge led control */
//#define CONFIG_TCT_CHARGE_LED_CONTROL
/* [PLATFORM]-Add-END by TCTSZ.pingao.yang */

/* [PLATFORM]-Add-BEGIN by TCTSZ.pingao.yang, 09/07/2015,  add charge control */
#define CONFIG_TCT_CHARGE_CONTROL
/* [PLATFORM]-Add-END by TCTSZ.pingao.yang */

/* [PLATFORM]-Add-BEGIN by TCTSZ.pingao, 09/09/2015,  change charge current */
#define CONFIG_TCT_LIMIT_USB_CURRENT
#define STANDARD_HOST_CURRENT 490
#define ICHARGING_DIFF 20
/* [PLATFORM]-Add-END by TCTSZ.pingao.yang, 09/09/2015 */

/* [PLATFORM]-Add-BEGIN by TCTSZ.pingao, 10/19/2015,  define tct temperature algorithm */
#define TCT_TEMPERATURE_ALGORITHM
#ifdef TCT_TEMPERATURE_ALGORITHM
#define TEMPERATURE_AVERAGE_SIZE	8
#endif
/* [PLATFORM]-Add-END by TCTSZ.pingao.yang, 10/19/2015 */

#define MTK_TEMPERATURE_RECHARGE_SUPPORT

#ifdef CONFIG_MTK_FAN5405_SUPPORT
#define FAN5405_BUSNUM 1
#endif
#endif /* _CUST_BAT_H_ */
