include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y += focaltech_core.o
obj-y += focaltech_ctl.o
obj-y += focaltech_ex_fun.o
obj-y += focaltech_flash.o
obj-y += focaltech_Gesture.o
obj-y += ft_gesture_lib.a

